services:
  api:
    depends_on:
      - db
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/usersdb
      - SECRET_KEY=12aea35700b2a225ee9364131d9d5fbb6de89bb038a660b66c4889a0a44adf05
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:


