version: 2.1
orbs:
  python: circleci/python@2.0.3
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test:
    docker:
        - image: cimg/python:3.14.6
          environment:
            DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/usersdb_test
            SECRET_KEY: 12aea35700b2a225ee9364131d9d5fbb6de89bb038a660b66c4889a0a44adf05
        - image: cimg/postgres:15.0
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: usersdb_test
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install test coverage tools
          command: pip install pytest-cov coveralls
      - run:
          name: Run tests with coverage
          command: python -m pytest --cov=src --cov-report=xml
      - run:
          name: Upload coverage to Coveralls
          command: coveralls
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test